version: "3.7"

services:
  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    deploy:
      mode: global
    configs:
      - source: registry_config
        target: /etc/docker/registry/config.yml
        mode: 0440

configs:
  registry_config:
    external: true
